### PR TITLE
Jump between paragraph ends; ignore blank lines

### LINKED ISSUE #4: Skips over lines that only contain spaces/tabs.
Lines with spaces/tabs are skipped over.
You can just update `s = self.view.substr(line)`  on both lines 61 & 87 
to `s = self.view.substr(line).strip(" \t")`.

And thank you for creating this plugin! :+1:

### PR DESCRIPTION
**Pull request by xsleonard**
Alternate implementation of #5 
Fixes #4

### CODE REVIEW

**Comment by Zankoku-Okuno** [comment]
One bug I happened across here is that if the cursor is at the end of a line in the middle of a paragraph, it just moves to the next line when going forwards. There doesn't seem to be a similar problem going backwards, though.

**Comment by xsleonard** [comment]
I fixed that bug now; the issue was that `self.view.split_by_lines()` would not include the line that the cursor was at the end of. `self.view.lines()` returns all lines that intersect the cursor region, so it does include it.

**Comment by xsleonard** [comment]
Test again, I think I did more thorough checks this time but would like to make sure

**Comment by Zankoku-Okuno** [comment]
I tried out all the stuff I've thought to test before, and everything looks good.

**Comment by xsleonard** [comment]
Thanks for your help

**Pull request merged**
